import type { Metadata } from 'next';
import { Instrument_Sans } from 'next/font/google';
import './globals.css';
import './form.css';
import Header from './components/sections/header';

const font = Instrument_Sans({
  subsets: ['latin'],
  variable: '--font',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.variable}>
        <Header />
        {children}
        <footer>
          <p>&copy; {new Date().getFullYear()} Career Weaver. All rights reserved</p>
        </footer>
      </body>
    </html>
  );
}
